### ISSUE TITLE
Can't wake up car after update from 0.2.0 to latest (0.5.0)

### ISSUE THREAD

**Issue by jurviz** [iainbullock/tesla_ble_mqtt_docker#112]
I'm trying to update to the latest release. I have deleted device in MQTT before. Release 0.2.0 was still working as tested yesterday.
All sensors have state unknown.
Here is the log after updating to latest release:

2025-04-02T16:03:12.916224244Z [16:03:12] Starting... loading /app/env.sh
2025-04-02T16:03:12.919259243Z [16:03:12] loading libproduct.sh
2025-04-02T16:03:12.945237145Z [0;36mSetting up MQTT clients with authentication[0m
2025-04-02T16:03:12.965980438Z [0;32mCore version is 0.5.0[0m
2025-04-02T16:03:12.966103530Z [0;32mConfiguration Options are:
2025-04-02T16:03:12.966126573Z   TC_COMMAND_TIMEOUT=5
2025-04-02T16:03:12.966145241Z   TC_CONNECT_TIMEOUT=10
2025-04-02T16:03:12.966162159Z   TC_KILL_TIMEOUT=25
2025-04-02T16:03:12.966179660Z   POLL_STATE_LOOP_DELAY=30
2025-04-02T16:03:12.966196578Z   DEBUG=false
2025-04-02T16:03:12.966214954Z   MQTT_SERVER=192.168.8.159
2025-04-02T16:03:12.966233330Z   MQTT_PORT=1883
2025-04-02T16:03:12.966249957Z   MQTT_PASSWORD=Not Shown
2025-04-02T16:03:12.966267458Z   MQTT_USERNAME=ha
2025-04-02T16:03:12.966284376Z   PRESENCE_DETECTION_LOOP_DELAY=300
2025-04-02T16:03:12.966301293Z   PRESENCE_DETECTION_TTL=360
2025-04-02T16:03:12.966318795Z   VIN_LIST=5YJ3E7EB0KF262106
2025-04-02T16:03:12.966336004Z   MAX_CURRENT=16
2025-04-02T16:03:12.966353505Z   NO_POLL_SECTIONS=
2025-04-02T16:03:12.966371006Z   BLE_HCI_NUM=0
2025-04-02T16:03:12.966387924Z   IMMEDIATE_UPDATE=true[0m
2025-04-02T16:03:12.966404842Z [0;32m  ENABLE_HA_FEATURES=true[0m
2025-04-02T16:03:13.998987406Z [0;32mMQTT derived variables for vin=5YJ3E7EB0KF262106 are: 
2025-04-02T16:03:13.999111373Z   var_5YJ3E7EB0KF262106_polling=on
2025-04-02T16:03:13.999138791Z   var_5YJ3E7EB0KF262106_polling_interval=660[0m
2025-04-02T16:03:14.006062265Z [0;36mRemoving single buttons to be replaced by switches & covers:[0m
2025-04-02T16:03:14.006175148Z [0;36mwindows, charger, charge-port, climate, trunk[0m
2025-04-02T16:03:14.006204316Z [0;36mdelete_legacies_singles; deleting legacy single MQTT entities topics[0m
2025-04-02T16:03:14.303977261Z [0;32mvin:5YJ3E7EB0KF262106 presence has expired, set presence ON[0m
2025-04-02T16:03:29.848362814Z [0;36msetupHADiscoveryAllVINsMain; Discarding unread MQTT messages for command and config topics[0m
2025-04-02T16:03:29.861423665Z [0;36mListening for Home Assistant Start (in background)[0m
2025-04-02T16:03:29.861975536Z [0;32mEntering main loop...[0m
2025-04-02T16:03:29.862154048Z [0;36mmain loop; Launching background listen_to_mqtt_loop...[0m
2025-04-02T16:03:29.865063622Z [0;36mmain loop; Launching background poll_state_loop...[0m
2025-04-02T16:03:29.865247093Z [0;32mmain loop; launch BLE scanning for car presence every 300 seconds[0m
2025-04-02T16:03:29.865338391Z [0;36mEntering poll_state_loop...[0m
2025-04-02T16:03:29.867096094Z [0;36mEntering Listen to MQTT loop...[0m
2025-04-02T16:03:29.867251563Z [0;32mLaunching listen_to_mqtt[0m
2025-04-02T16:03:29.867289774Z [0;32mListening to MQTT[0m
2025-04-02T16:03:40.309760300Z [0;32mvin:5YJ3E7EB0KF262106 ble_ln:S89e7254b656017caC match:(S89e7254b656017caC|80:6F:B0:22:DC:8D) presence detected[0m
2025-04-02T16:03:40.309876975Z [0;32mvin:5YJ3E7EB0KF262106 presence has expired, set presence ON[0m
2025-04-02T16:08:21.367416287Z [0;32mReceived MQTT message; topic:tesla_ble/5YJ3E7EB0KF262106/command msg:wake vin:5YJ3E7EB0KF262106 cmd:command[0m
2025-04-02T16:08:21.370321777Z [0;36msendBLECommand: Attempt 1/5 sending Wake up vehicle to vin:5YJ3E7EB0KF262106 command:-domain vcsec wake[0m
2025-04-02T16:08:21.509803688Z [0;32mCar is not responding to bluetooth, it's probably away VIN:5YJ3E7EB0KF262106[0m
2025-04-02T16:08:21.519562356Z [0;36msendBLECommand; Retrying....[0m
2025-04-02T16:08:21.519695948Z [0;36msendBLECommand: Attempt 2/5 sending Wake up vehicle to vin:5YJ3E7EB0KF262106 command:-domain vcsec wake[0m
2025-04-02T16:08:22.862835487Z jq: parse error: Invalid numeric literal at line 1, column 11
2025-04-02T16:08:22.863899559Z [0;32mCar is present but asleep VIN:5YJ3E7EB0KF262106. Attempting to wake it[0m
2025-04-02T16:08:23.169988195Z 2025/04/02 16:08:23 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:23.170909050Z 2025/04/02 16:08:23 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:31.892458257Z [0;36msendBLECommand; Retrying....[0m
2025-04-02T16:08:31.892592433Z [0;36msendBLECommand: Attempt 3/5 sending Wake up vehicle to vin:5YJ3E7EB0KF262106 command:-domain vcsec wake[0m
2025-04-02T16:08:32.783775237Z jq: parse error: Invalid numeric literal at line 1, column 11
2025-04-02T16:08:32.785322052Z [0;32mCar is present but asleep VIN:5YJ3E7EB0KF262106. Attempting to wake it[0m
2025-04-02T16:08:33.149741300Z 2025/04/02 16:08:33 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:33.151118936Z 2025/04/02 16:08:33 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:41.247248007Z [0;36msendBLECommand; Retrying....[0m
2025-04-02T16:08:41.247385391Z [0;36msendBLECommand: Attempt 4/5 sending Wake up vehicle to vin:5YJ3E7EB0KF262106 command:-domain vcsec wake[0m
2025-04-02T16:08:42.251215231Z jq: parse error: Invalid numeric literal at line 1, column 11
2025-04-02T16:08:42.252391020Z [0;32mCar is present but asleep VIN:5YJ3E7EB0KF262106. Attempting to wake it[0m
2025-04-02T16:08:42.539225714Z 2025/04/02 16:08:42 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:42.540162028Z 2025/04/02 16:08:42 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:50.646436833Z [0;36msendBLECommand; Retrying....[0m
2025-04-02T16:08:50.646570133Z [0;36msendBLECommand: Attempt 5/5 sending Wake up vehicle to vin:5YJ3E7EB0KF262106 command:-domain vcsec wake[0m
2025-04-02T16:08:50.776962507Z [0;32mvin:5YJ3E7EB0KF262106 ble_ln:S89e7254b656017caC match:(S89e7254b656017caC|80:6F:B0:22:DC:8D) presence detected[0m
2025-04-02T16:08:51.826016021Z jq: parse error: Invalid numeric literal at line 1, column 11
2025-04-02T16:08:51.828646451Z [0;32mCar is present but asleep VIN:5YJ3E7EB0KF262106. Attempting to wake it[0m
2025-04-02T16:08:52.299993927Z 2025/04/02 16:08:52 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:08:52.300808608Z 2025/04/02 16:08:52 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-02T16:09:00.397677976Z [0;36msendBLECommand; Retrying....[0m
2025-04-02T16:09:00.397820903Z [1;32msendBLECommand; max retries unsuccessfully trying to send command -domain vcsec wake to 5YJ3E7EB0KF262106[0m

**Comment by jurviz** [comment]
Do i have to regen/redeploy the key to the car?

**Comment by iainbullock** [comment]
> Do i have to regen/redeploy the key to the car?

No your key is working. 

I'm travelling this week so will look at your logs later when I can. 

Interested that it used to work on v0.2.0, as my first impression is the Bluetooth is too far from the car

What hardware are you using, how far away it is,and what car / year do you have?

Thanks

**Comment by jurviz** [comment]
My car is a Model 3, registered 3/2019 (Firmware 2025.8.6). My system (Home Assistant , mosquitto, tesla-local-control) is running on an Odroid M1 in the garage next to the car at a distance of about 1.5m. The bluetooth dongle is an Odroid 5BK.
hciconfig output:

hci0:   Type: Primary  Bus: USB
        BD Address: E0:E1:A9:33:CA:04  ACL MTU: 1021:8  SCO MTU: 255:12
        UP RUNNING 
        RX bytes:1038193 acl:0 sco:0 events:38751 errors:0
        TX bytes:1044766 acl:12856 sco:0 commands:41654 errors:0

I will use 0.2.0 for now.

**Comment by jurviz** [comment]
Even if the car is awake and i try to wake the car the same error messages appear.

**Comment by iainbullock** [comment]
Thanks for the update. There should be no issues with the car or the distance away. 

The underlying tesla-control package has changed the requirements of the bluetooth hardeware since v0.2.0, maybe that's the issue. We know it is very fussy about hardware. 

The only thing I can suggest is try try different Bluetooth hardware. Some users have tried other USB devices and run into issues. It is difficult to conclusively say which hardware works and which doesn't.

I can say Raspberry Pi 3b+ using its built in bluetooth hardware works for me with no issues. Most other users of RPi with built in bluetooth generally report success

**Comment by jurviz** [comment]
I will try to find another dongle. Until then i'll stick to release 0.2.0 as it works for solar excess charging.
I will report any outcome.

**Comment by top-gun** [comment]
What Iain says: The native bt radio in the Raspi seems to be the most stable atm - not necessarily because it‘s so well built, but because the bt drivers for other hardware are not as stable as we need. On my Raspi 4, I tried a modern BT 5.4 dongle, and had to reboot the pi after just a few hours because the device disappeared as HCI1 and reappeared as HCI2. I went bacj to the built-in radio and now it‘s pretty stable. The issues I had were actually not caused by the hardware anyway.

**Comment by jurviz** [comment]
I did some tests using the sh shell of the tesla-ble-mqtt container and i could send wake command and other commands. So i can say that the communication via BLE to the car is working. I can see the result of wake and charging-set-amps in the Tesla app on my android smartphone.
Here is the log from the shell:

/share/tesla_ble_mqtt # tesla-control -ble -debug -vin 5YJ3E7EB0KF262106 -key-file /share/tesla_ble_mqtt/
5YJ3E7EB0KF262106_private.pem wake 2>&1
2025-04-03T19:23:23Z [debug] Set session cache file to '/root/.tesla-cache.json'
2025-04-03T19:23:23Z [debug] Set OAuth token name to ''
2025-04-03T19:23:23Z [debug] Set OAuth token file to ''
2025-04-03T19:23:23Z [debug] Set keyring type to ''
2025-04-03T19:23:23Z [debug] Set keyring Debug Logging to 'false'
2025-04-03T19:23:23Z [debug] Loading cache from /root/.tesla-cache.json...
2025-04-03T19:23:23Z [debug] Client public key: 04ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a
2025-04-03T19:23:23Z [debug] Connecting over BLE...
2025-04-03T19:23:23Z [debug] Creating new BLE device
2025-04-03T19:23:24Z [debug] Dialing to 80:6f:b0:22:dc:8d (S89e7254b656017caC)...
2025-04-03T19:23:24Z [debug] Discovering services 80:6f:b0:22:dc:8d...
2025/04/03 19:23:24 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025/04/03 19:23:24 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-03T19:23:24Z [info ] Connected to vehicle BLE
2025-04-03T19:23:24Z [info ] Connecting to car...
2025-04-03T19:23:24Z [info ] Starting dispatcher service...
2025-04-03T19:23:24Z [info ] Securing connection...
2025-04-03T19:23:24Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2025-04-03T19:23:24Z [debug] TX: 320208023a121210d769fbc52ac2e1099ef3f9664e228f269a031002f958914e1e8879f2e0202d08ac64d7a003025202093e6a80010a430a4104ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a2a390a1098096d461148d51e34ab8d1a2a5184c3120caef06140ce8aafebfdf46488181425260000002a1071fa09ea0fdcc465137dd6eadaf61b47
2025-04-03T19:23:25Z [debug] RX: 32121210d769fbc52ac2e1099ef3f9664e228f263a0208026a244a220a0c51e8aa5b2c069fa14f12c8af10021a10eb1f73bbfda8b5d387dc1ac737ca7da892031002f958914e1e8879f2e0202d08ac64d7
/share/tesla_ble_mqtt # tesla-control -ble -debug -vin 5YJ3E7EB0KF262106 -key-file /share/tesla_ble_mqtt/
5YJ3E7EB0KF262106_private.pem honk 2>&1
2025-04-03T19:30:16Z [debug] Set session cache file to '/root/.tesla-cache.json'
2025-04-03T19:30:16Z [debug] Set OAuth token name to ''
2025-04-03T19:30:16Z [debug] Set OAuth token file to ''
2025-04-03T19:30:16Z [debug] Set keyring type to ''
2025-04-03T19:30:16Z [debug] Set keyring Debug Logging to 'false'
2025-04-03T19:30:16Z [debug] Loading cache from /root/.tesla-cache.json...
2025-04-03T19:30:16Z [debug] Client public key: 04ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a
2025-04-03T19:30:16Z [debug] Connecting over BLE...
2025-04-03T19:30:16Z [debug] Creating new BLE device
2025-04-03T19:30:17Z [debug] Dialing to 80:6f:b0:22:dc:8d (S89e7254b656017caC)...
2025-04-03T19:30:17Z [debug] Discovering services 80:6f:b0:22:dc:8d...
2025/04/03 19:30:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025/04/03 19:30:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-03T19:30:17Z [info ] Connected to vehicle BLE
2025-04-03T19:30:17Z [info ] Connecting to car...
2025-04-03T19:30:17Z [info ] Starting dispatcher service...
2025-04-03T19:30:17Z [info ] Securing connection...
2025-04-03T19:30:17Z [info ] Requesting session info from DOMAIN_INFOTAINMENT
2025-04-03T19:30:17Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2025-04-03T19:30:17Z [debug] TX: 320208033a121210be9b206191285ffa74f5df0dbfb901ef9a0310ec81901bc62cfca9872dcd930b27a3a372430a4104ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a
2025-04-03T19:30:18Z [debug] RX: 32121210be9b206191285ffa74f5df0dbfb901ef3a0208037a5f08f201124104396f522df6e50f2c01cf891e37e9576124e16715b1a9bc826617bac4365ee3914425ce52c2af74c930d573ea93c4b5d99983184e07ed2acad794a85efd67339d1a1081d0fc0c01ed8f92b311bf18fd82b426250e44030030066a2432220a2010f461e1f0f16c4ede37cdb415807fb0de8c6c31df7c3ca9aa644f4912fe9a3c920310ec81901bc62cfca9872dcd930b27a3a3
2025-04-03T19:30:18Z [info ] [ec81901bc62cfca9872dcd930b27a3a3] Updated session info for DOMAIN_INFOTAINMENT
2025-04-03T19:30:18Z [debug] TX: 320208033a121210be9b206191285ffa74f5df0dbfb901ef9a0310024dda21385fd6f1ae986e8480e997e2a00302520560397d27fe6a81010a430a4104ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a2a3a0a1081d0fc0c01ed8f92b311bf18fd82b426120cfa5ab6094639f0ceeffef82818f30125134403002a109c02c75903ed35934d4a3b3976cd567c
2025-04-03T19:30:18Z [debug] RX: 320208003a020802521f1a1d12160a14bc4c60cd14c75fd42780d997aa3104cdb9bc07c61802220101
2025-04-03T19:30:18Z [debug] [00] Dropping message to DOMAIN_BROADCAST
2025-04-03T19:30:19Z [debug] RX: 32121210be9b206191285ffa74f5df0dbfb901ef3a020803520221c36a244a220a0c986f66851545030edc62c32910011a106fb0d0a1ee50a84e92b6a91f1afc8816920310024dda21385fd6f1ae986e8480e997e29a03102d052a65b934aa2596b469d3e81695ff
/share/tesla_ble_mqtt # tesla-control -ble -debug -vin 5YJ3E7EB0KF262106 -key-file /share/tesla_ble_mqtt/
5YJ3E7EB0KF262106_private.pem ping 2>&1
2025-04-03T19:32:25Z [debug] Set session cache file to '/root/.tesla-cache.json'
2025-04-03T19:32:25Z [debug] Set OAuth token name to ''
2025-04-03T19:32:25Z [debug] Set OAuth token file to ''
2025-04-03T19:32:25Z [debug] Set keyring type to ''
2025-04-03T19:32:25Z [debug] Set keyring Debug Logging to 'false'
2025-04-03T19:32:25Z [debug] Loading cache from /root/.tesla-cache.json...
2025-04-03T19:32:25Z [debug] Client public key: 04ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a
2025-04-03T19:32:25Z [debug] Connecting over BLE...
2025-04-03T19:32:25Z [debug] Creating new BLE device
2025-04-03T19:32:25Z [debug] Dialing to 80:6f:b0:22:dc:8d (S89e7254b656017caC)...
2025-04-03T19:32:25Z [debug] Discovering services 80:6f:b0:22:dc:8d...
2025/04/03 19:32:25 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025/04/03 19:32:25 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-03T19:32:26Z [info ] Connected to vehicle BLE
2025-04-03T19:32:26Z [info ] Connecting to car...
2025-04-03T19:32:26Z [info ] Starting dispatcher service...
2025-04-03T19:32:26Z [info ] Securing connection...
2025-04-03T19:32:26Z [info ] Session for DOMAIN_INFOTAINMENT loaded from cache
2025-04-03T19:32:26Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2025-04-03T19:32:26Z [debug] TX: 320208033a1212109799550a162c74a8689b867f7239e2169a0310e7ea8da3c9415b4a5cb018186191c16ca003025207d45cc55a1718d16a81010a430a4104ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a2a3a0a1081d0fc0c01ed8f92b311bf18fd82b426120c58f8979aa9dbf533228b245918f40125914403002a107a866f094bfd289403a6d16db59dfb15
2025-04-03T19:32:26Z [debug] RX: 321212109799550a162c74a8689b867f7239e2163a02080352167d61394a965aabe27caaefa9b8a92770e9935adb66ab6a244a220a0c3ca8a1a67375bd171c7910e410011a1075eb1610090579943fae477eb9a42a5e920310e7ea8da3c9415b4a5cb018186191c16c9a0310c9be131d80d1dbaf435dfd925cc33d13
/share/tesla_ble_mqtt # 
/share/tesla_ble_mqtt # tesla-control -ble -debug -vin 5YJ3E7EB0KF262106 -key-file /share/tesla_ble_mqtt/
5YJ3E7EB0KF262106_private.pem charging-set-amps 10 2>&1
2025-04-03T19:36:16Z [debug] Set session cache file to '/root/.tesla-cache.json'
2025-04-03T19:36:16Z [debug] Set OAuth token name to ''
2025-04-03T19:36:16Z [debug] Set OAuth token file to ''
2025-04-03T19:36:16Z [debug] Set keyring type to ''
2025-04-03T19:36:16Z [debug] Set keyring Debug Logging to 'false'
2025-04-03T19:36:16Z [debug] Loading cache from /root/.tesla-cache.json...
2025-04-03T19:36:16Z [debug] Client public key: 04ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a
2025-04-03T19:36:16Z [debug] Connecting over BLE...
2025-04-03T19:36:16Z [debug] Creating new BLE device
2025-04-03T19:36:16Z [debug] Dialing to 80:6f:b0:22:dc:8d (S89e7254b656017caC)...
2025-04-03T19:36:17Z [debug] Discovering services 80:6f:b0:22:dc:8d...
2025/04/03 19:36:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025/04/03 19:36:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025-04-03T19:36:17Z [info ] Connected to vehicle BLE
2025-04-03T19:36:17Z [info ] Connecting to car...
2025-04-03T19:36:17Z [info ] Starting dispatcher service...
2025-04-03T19:36:17Z [info ] Securing connection...
2025-04-03T19:36:17Z [info ] Session for DOMAIN_INFOTAINMENT loaded from cache
2025-04-03T19:36:17Z [info ] Session for DOMAIN_VEHICLE_SECURITY loaded from cache
2025-04-03T19:36:17Z [debug] TX: 320208033a121210b0ae79629510aab11b551d48f5c2e8409a03100aa1e9684371378fe411ef6d33c26adfa003025207a5d6a50b3dd97d6a81010a430a4104ad60dd8745cc4b764ebd2bfb97def26c6b485594fab06d336c47bdeb29f8edf94f8aed1c7e06132938b1f5910f58d5b63d4eab65b8af3f60708482c22bf76d1a2a3a0a1081d0fc0c01ed8f92b311bf18fd82b426120c7afa2f446974285f50006cdc18f50125784503002a10747bf8eb64edbaa976e129827507e478
2025-04-03T19:36:18Z [debug] RX: 32121210b0ae79629510aab11b551d48f5c2e8403a0208035202bdd26a244a220a0c915b59e8d3d2110cf0c30ef110011a1055efc0fa5b763195a9a5887d05c82b129203100aa1e9684371378fe411ef6d33c26adf9a03104fa496926e2e5d8f00c1260a23ea4284

Despite these messages 
2025/04/03 19:36:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
2025/04/03 19:36:17 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
the command seems to be completed by the car.

**Comment by iainbullock** [comment]
To confirm if you send a command via the command line it works despite the various error messages, but if you send via this application it doesn't (because the code thinks the car is not present or asleep so doesn't send the actual command). 

If you can confirm this is the case, then a workaround will be possible. 

As you seem to know how to access the command line inside the container, can you add a diagnostic line into /app/tesla-commands.sh? Look for these lines (23-33). You might turn off debugging before doing this, so the logs are cleaner:
```
   # Get presence and awake status via body-controller-state
    set +e
    bcs_json=$(timeout -k 1 -s SIGKILL $TC_KILL_TIMEOUT /usr/bin/tesla-control -ble -vin $vin -command-timeout ${TC_COMMAND_TIMEOUT}s -connect-timeout ${TC_CONNECT_TIMEOUT}s body-controller-state 2>&1)
    EXIT_VALUE=$?
    set -e
    wait

    # If exit code is 137 then the tesla-control process had to be killed
    if [ $EXIT_VALUE -eq 137 ]; then
      log_warning "sendBLECommand (BCS): tesla_control process was killed. This may indicate that the bluetooth adapter is struggling to keep up with the rate of commands"
      log_warning "See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142"
```
Add in a line `echo Exit Value $EXIT_VALUE` as shown
```
   # Get presence and awake status via body-controller-state
    set +e
    bcs_json=$(timeout -k 1 -s SIGKILL $TC_KILL_TIMEOUT /usr/bin/tesla-control -ble -vin $vin -command-timeout ${TC_COMMAND_TIMEOUT}s -connect-timeout ${TC_CONNECT_TIMEOUT}s body-controller-state 2>&1)
    EXIT_VALUE=$?
    set -e
    wait

echo Exit Value $EXIT_VALUE

    # If exit code is 137 then the tesla-control process had to be killed
    if [ $EXIT_VALUE -eq 137 ]; then
      log_warning "sendBLECommand (BCS): tesla_control process was killed. This may indicate that the bluetooth adapter is struggling to keep up with the rate of commands"
      log_warning "See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142"
```
When you restart the container, let's see what the return value is from the body-controller-state call

**Comment by jurviz** [comment]
[tesla_ble_mqtt-2025-04-04T12-11-17.log](https://github.com/user-attachments/files/19604143/tesla_ble_mqtt-2025-04-04T12-11-17.log)

I have attached the trace.

**Comment by jurviz** [comment]
[tesla_ble_mqtt-2025-04-04T12-26-38.log](https://github.com/user-attachments/files/19604341/tesla_ble_mqtt-2025-04-04T12-26-38.log)
Added some more echos

**Comment by iainbullock** [comment]
Ok so the exit code is normal, let's have a look at the actual JSON. Can you add a line beneath the previously added as follows:
```
echo BCS JSON $bcs_json
```

**Comment by jurviz** [comment]
Already done, see 2nd log. Deleted "2>&1" at end of line 25 and it seems to work. 
Attach new log.

[tesla_ble_mqtt-2025-04-04T12-56-18.log](https://github.com/user-attachments/files/19604807/tesla_ble_mqtt-2025-04-04T12-56-18.log)

**Comment by iainbullock** [comment]
Ah I see the error messages on the standard error are getting combined with the JSON on the standard output which messes up the parsing of the JSON. 

No idea why you are getting the error messages, but I should be able to fix.

Can you patch in the meantime, I will release a dev version with this fix when I get chance

Excellent spot thanks for suggesting the fix!

**Comment by jurviz** [comment]
I will keep the patched version until you release a fix.
I'm on the latest available firmware for the car. May be Tesla changed some of their code again.

**Comment by jurviz** [comment]
Patched also read-state.sh, line 70.

**Comment by jurviz** [comment]
The error message stems from here. It is an event for a missing command. Whatever that means?
[https://github.com/go-ble/ble/blob/8c5522f543335a80e18fc70e704b104cf3fcc606/linux/hci/hci.go#L462C4-L462C63](url)

**Comment by iainbullock** [comment]
Agreed. I don't know what it means though. I assume something in the hardware / driver is not supported

**Comment by jurviz** [comment]
I also found the error message in dmesg. I suspect it is a driver problem with my ubuntu kernel, wich is still 5.19.17 from hardkernel for the Odroid M1. It is probably a driver problem for the Realtek chip. I will stay with the patched version until i can either try to update the kernel to a more recent version or change the dongle to another one. 
The car is charged by solar excess now and the amperage is adjusted via BLE. I will use the patched version, so no need to fix it just for me.

**Comment by iainbullock** [comment]
Thanks but I will change it as others may benefit. Also I think redirecting the standard error into the standard output might break something if (when) Tesla change something in the future. I will mod the code to bring them out seperately.

It was a good spot by you, so worth the time to remove it as a potential issue

**Comment by iainbullock** [comment]
I've released v0.5.2-dev to DockerHub which includes this and some other improvements / fixes

If you get chance to test and feedback it would be appreciated. Thanks for your input

**Comment by jurviz** [comment]
I have just pulled and activated 0.5.2-dev. I don't see any problems in the communication with the car. I can send the wake command to wake up the car, honk the horn and the solar excess charging is working also.
The error messages still appear, but don't impede the function.

**Comment by jurviz** [comment]
Thank you for the fix and for the software.

**Comment by iainbullock** [comment]
Excellent I'll close this one now thanks for the feedback

**Comment by notreallybob** [comment]
This is still happening, getting almost consistent 'Got an unregistered notification' at the end of the json.
Running on rpi zero w 1.1, using 0.5.2-dev.
Tracked it down to tesla_commands.sh like @jurviz above. It boils down to the 2 calls to /usr/bin/tesla-control, one of which @jurviz changed stderr redirection to /dev/null. ie. 2>/dev/null.
I made changes to the 2nd call to /usr/bin/tesla-control. This binary file prints to stderr to display warnings or information. Redirecting error/info messages to stdout will screw up json syntax. So I changed the call, redirecting stderr to a temporary file and if there was content in that temporary file, then I logged it. This way you don't contaminate the json.
The temporary file cleanup is handled too. This change might negate the need for https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/74

I also made other small changes:
- Use of "local" for local scoping variables is usually advisable.
- Quoting variables is also usually advisable. eg.
`rqdValue=$(echo $stateJSON | jq -e $jsonParam)` should be 
`rqdValue=$(echo "$stateJSON" | jq -e "$jsonParam")`, especially if `$stateJSON` is multiline.
- Perhaps even replacing echo with printf like:
`rqdValue=$(printf "%s\n" "$stateJSON" | jq -e "$jsonParam")`

I don't know how to use git/github, so I'm clueless with pull/merge/anything...so I'm including the sendBLECommand() function inline:

```
sendBLECommand() {
  local vin="$1"
  local command="$2"
  local commandDescription="$3"

  # Prepare for calling tesla-control
  export TESLA_VIN="$vin"
  export TESLA_KEY_FILE="$KEYS_DIR/${vin}_private.pem"
  export TESLA_KEY_NAME="$KEYS_DIR/${vin}_private.pem"

  # NOTBOB
  # Create a single temp file for the duration of the function
  local ble_error;
  local tmp_stderr=$(mktemp) || {
    echo "Failed to create temp file for stderr" >&2
    return 1
  }

  # Set up cleanup trap (ash supports trap, though limited)
  trap 'rm -f "$tmp_stderr"; return' EXIT INT TERM

  # Retry loop
  max_retries=5
  for sendCommandCount in $(seq $max_retries); do

    log_notice "sendBLECommand: Attempt $sendCommandCount/${max_retries} sending $commandDescription to vin:$vin command:$command"

    # Get presence and awake status via body-controller-state
    set +e
    bcs_json=$(timeout -k 1 -s SIGKILL $TC_KILL_TIMEOUT /usr/bin/tesla-control -ble -vin "$vin" -command-timeout ${TC_COMMAND_TIMEOUT}s -connect-timeout ${TC_CONNECT_TIMEOUT}s body-controller-state 2>/dev/null)
    EXIT_VALUE=$?
    set -e
    wait

    # If exit code is 137 then the tesla-control process had to be killed
    if [ $EXIT_VALUE -eq 137 ]; then
      log_warning "sendBLECommand (BCS): tesla_control process was killed. This may indicate that the bluetooth adapter is struggling to keep up with the rate of commands"
      log_warning "See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142"

    # If non zero, car is not contactable by bluetooth
    elif [ $EXIT_VALUE -ne 0 ]; then
      log_info "Car is not responding to bluetooth, it's probably away VIN:$vin"
      # Publish to MQTT presence_bc sensor. TODO: Set awake sensor to Unknown via MQTT availability
      stateMQTTpub $vin 'false' 'binary_sensor/presence_bc'

    else
      # Car has responded
      log_debug "Car has responded to bluetooth, it is present. VIN:$vin"
      stateMQTTpub "$vin" 'true' 'binary_sensor/presence_bc'

      # Check if awake or asleep from the body-controller-state response
      #rqdValue=$(echo $bcs_json | jq -e '.vehicleSleepStatus')
      rqdValue=$(printf "%s\n" "$bcs_json" | jq -e '.vehicleSleepStatus')
      EXIT_VALUE=$?
      if [ $EXIT_VALUE -ne 0 ] || [ "$rqdValue" != "\"VEHICLE_SLEEP_STATUS_AWAKE\"" ]; then
        log_info "Car is present but asleep VIN:$vin. Attempting to wake it"

        stateMQTTpub "$vin" 'false' 'binary_sensor/awake'

        # Send wake command
        set +e
        timeout -k 1 -s SIGKILL $TC_KILL_TIMEOUT tesla-control -ble -command-timeout ${TC_COMMAND_TIMEOUT}s -connect-timeout ${TC_CONNECT_TIMEOUT}s -domain vcsec wake
        EXIT_STATUS=$?
        set -e
        wait
        # If exit code is 137 then the tesla-control process had to be killed
        if [ $EXIT_STATUS -eq 137 ]; then
          log_warning "sendBLECommand (wake): tesla_control process was killed. This may indicate that the bluetooth adapter is struggling to keep up with the rate of commands"
          log_warning "See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142"
        fi
        sleep 7

      else
        log_info "Car is present and awake VIN:$vin, sending command"
        stateMQTTpub $vin 'true' 'binary_sensor/awake'

	ble_error="" # NOTBOB
        # Send command to car
        set +e
	# NOTBOB: this relies on $command being unquoted. ie. 'command' carries multiple args such as 'state climate'
        TESLACTRLOUT=$(timeout -k 1 -s SIGKILL $TC_KILL_TIMEOUT /usr/bin/tesla-control -ble -command-timeout ${TC_COMMAND_TIMEOUT}s -connect-timeout ${TC_CONNECT_TIMEOUT}s $command 2>"$tmp_stderr")
        EXIT_STATUS=$?
        set -e
        wait

	# NOTBOB: read stderr from tmp file, truncate tmp file, log extraneous output
	ble_error=$(cat "$tmp_stderr")
	>"$tmp_stderr"
	if [ ! -z "$ble_error" ]; then
          log_error "tesla_control command='$command' extraneous output: $ble_error"
	fi


        # If exit code is 137 then the tesla-control process had to be killed
        if [ $EXIT_STATUS -eq 137 ]; then
          log_warning "sendBLECommand (cmd): tesla_control process was killed. This may indicate that the bluetooth adapter is struggling to keep up with the rate of commands"
          log_warning "See https://github.com/tesla-local-control/tesla_ble_mqtt_core/issues/142"

        elif [ $EXIT_STATUS -eq 0 ]; then
          log_debug "sendBLECommand; $TESLACTRLOUT"
          log_info "Command $command was successfully delivered to vin:$vin"
          stateMQTTpub $vin 'off' 'binary_sensor/last_cmd_status'
	  rm -f "$tmp_stderr" #NOTBOB
          return 0

        elif [[ "$TESLACTRLOUT" == *"car could not execute command"* ]]; then
          log_warning "sendBLECommand; $TESLACTRLOUT"
          log_warning "Skipping command $command to vin:$vin, not retrying"
          stateMQTTpub $vin 'on' 'binary_sensor/last_cmd_status'
	  rm -f "$tmp_stderr" #NOTBOB
          return 10

        elif [[ "$TESLACTRLOUT" == *"context deadline exceeded"* ]]; then
          log_warning "teslaCtrlSendCommand; $TESLACTRLOUT"
          log_warning "Vehicle might be asleep, though it shouldn't be as it was previously awake"

        else
          log_error "tesla-control send command:$command to vin:$vin failed exit status $EXIT_STATUS"
          log_error "sendBLECommand; $TESLACTRLOUT"

        fi

      fi

    fi

    log_notice "sendBLECommand; Retrying...."

  done

  # Max retries
  log_warning "sendBLECommand; max retries unsuccessfully trying to send command $command to $vin"
  stateMQTTpub $vin 'on' 'binary_sensor/last_cmd_status'
  rm -f "$tmp_stderr" #NOTBOB
  return 99
}

```

**Comment by iainbullock** [comment]
@notreallybob excellent work, thanks for sharing. I will put this in the next dev release. I'm working on other things at the moment, but when there are enough things here to change I will resume work on it
